name: test

on:
  push:
    branches: [ main ]

jobs:
  build-and-experiment:
    name: Build and Experiment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Get owner and repo
      run: |
        ownerrepo=${{ github.repository }}
        owner=$(echo $ownerrepo | cut -f1 -d/)
        if [[ "$owner" == "iter8-tools" ]]; then
          owner=iter8
        fi
        echo "OWNER=$owner" >> $GITHUB_ENV
        echo "REPO=$(echo $ownerrepo | cut -f2 -d/)" >> $GITHUB_ENV

    - name: echo
      run: |
        echo "commit: ${{ github.event.commits[0].id }}"
        echo "owner: ${{ env.OWNER }}"
        echo "repo: ${{ env.REPO }}"

    - name: Build and push server image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.OWNER }}/server:${{ github.event.commits[0].id }}
        file: Dockerfile
        push: true

