name: Cleanup 
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Test namespace'
        required: true
        default: 'test'

env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_RESOURCE_GROUP: 585330279c4b4175890b5c59dab786fb
  IBM_CLOUD_REGION: us-south
  # IKS_CLUSTER: kalantar-20211029-1 # name does not work
  IKS_CLUSTER: c5u1ej8d00c0squuquog # name or id of cluster
  NAMESPACE: ${{ github.event.inputs.namespace }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Cleanup"

        # Setup: Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: | 
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry


    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g default
        ibmcloud cr region-set "${IBM_CLOUD_REGION}"
        ibmcloud cr login

    - name: Identify target cluster
      run: |
        ibmcloud target -g $IBM_CLOUD_RESOURCE_GROUP
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl config current-context

    - run: kubectl delete --ignore-not-found namespace $NAMESPACE