name: Test Iter8 v2 GH action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  v0-10-3:
    runs-on: ubuntu-latest
    steps:
    - name: install Iter8 CLI
      uses: kalantar/iter8-run@v0.10.3
    - name: version
      run: | 
        iter8 version

  v0-10-4:
    runs-on: ubuntu-latest
    steps:
    - name: install Iter8 CLI
      uses: kalantar/iter8-run@v0.10.4
    - name: version
      run: | 
        iter8 version

  v0-10:
    runs-on: ubuntu-latest
    steps:
    - name: install Iter8 CLI
      uses: kalantar/iter8-run@v0.10
    - name: version
      run: | 
        iter8 version

  v0-9:
    runs-on: ubuntu-latest
    steps:
    - name: install Iter8 CLI
      uses: kalantar/iter8-run@v0.9
    - name: version
      run: | 
        iter8 version

  latest:
    runs-on: ubuntu-latest
    steps:
    - name: install Iter8 CLI
      uses: kalantar/iter8-run@latest
    - name: version
      run: | 
        iter8 version

